# Disable DNS server functionality
port=0

# Network interface to bind
interface=enp3s0
bind-interfaces

# ProxyDHCP mode: Listens for DHCP requests, does NOT hand out IP addresses,
# only supplies PXE boot options alongside your existing router DHCP server.
dhcp-range=192.168.1.0,proxy,255.255.255.0

# Built-in TFTP server configuration
enable-tftp
tftp-root=/home/mudhitha/System/Network-Installer/srv/tftp

# Client Architecture Matching (RFC 4578)
# 0 = BIOS x86/x64
# 6 = UEFI x86 (32-bit)
# 7 = UEFI x64 (64-bit standard)
# 9 = UEFI HTTP x64
# 11 = UEFI ARM64
dhcp-match=set:bios,option:client-arch,0
dhcp-match=set:efi-x86,option:client-arch,6
dhcp-match=set:efi-x64,option:client-arch,7
dhcp-match=set:efi-x64,option:client-arch,9
dhcp-match=set:efi-arm64,option:client-arch,11

# Bootloader files mapped per architecture
dhcp-boot=tag:bios,undionly.kpxe
dhcp-boot=tag:efi-x64,ipxe.efi
dhcp-boot=tag:efi-x86,ipxe32.efi
dhcp-boot=tag:efi-arm64,ipxe-arm64.efi

# PXE Menu Prompt
pxe-prompt="Network Installer PXE Booting...", 1
pxe-service=tag:bios,x86PC,"Boot Windows Network Installer (Legacy BIOS)",undionly.kpxe
pxe-service=tag:efi-x64,X86-64_EFI,"Boot Windows Network Installer (UEFI x64)",ipxe.efi
